# Main section (mandatory)
[hoa-exec]
# Name for the configuration
name = "My hoa-exec config"
# Config file version (mandatory)
version = 1

# Driver to use when an AP has not been given any driver
default-driver = "user"

[[driver.flip]]
aps = ["a"]
bias = 0.5  # Bias of picking "true" (optional, defaults to 0.5)

[[driver.user]]
aps = ["b"]
