# Main section (mandatory)
[hoa-exec]
# Name for the configuration
name = "My HOA config"
# Config file version (mandatory)
version = 1

# Driver to use when an AP has not been given any driver
default-driver = "user"

[driver.flip]
aps = ["a"]

[driver.user]
aps = ["b"]