[tool.poetry]
name = "hoa_exec"
version = "0.1.0"
description = "Execute a HOA automaton"
authors = ["Luca Di Stefano <luca.di.stefano@tuwien.ac.at>"]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
hoa-utils = {git = "https://github.com/lou1306/hoa-utils.git"}
typer = "^0.12.3"
msgspec = "^0.18.6"
tomli = "^2.0.1"
networkit = {git = "https://github.com/networkit/networkit.git@534044c", rev = "534044c"}
lark = "^1.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hoa_exec = "hoa_exec.main:app"

