[tool.poetry]
name = "hoa_exec"
version = "0.1.0"
description = "Execute a HOA automaton"
authors = ["Luca Di Stefano <luca.di.stefano@tuwien.ac.at>"]

[tool.poetry.dependencies]
python = "^3.10"
hoa-utils = {git = "https://github.com/lou1306/hoa-utils.git"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hoa_exec = "hoa_exec.main:main"

